# Generated by Django 6.0.1 on 2026-01-29 20:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Ej: Salmones del Sur S.A.', max_length=255)),
                ('tax_id', models.CharField(blank=True, help_text='RUT o Tax ID', max_length=50)),
                ('country', models.CharField(default='Chile', max_length=100)),
                ('type', models.CharField(choices=[('EXPORTER', 'Exportador'), ('IMPORTER', 'Importador')], default='EXPORTER', max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('UNCLAIMED', 'Sin reclamar'), ('SUSPENDED', 'Suspendido')], default='ACTIVE', max_length=10)),
                ('default_address', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, help_text='Email principal de la organización', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PackingVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Config',
                'verbose_name_plural': 'System Configs',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador'), ('OPERATOR', 'Operador')], default='OPERATOR', max_length=10)),
                ('is_platform_admin', models.BooleanField(default=False, help_text='Super Admin de Exportech')),
                ('invite_pending', models.BooleanField(default=False, help_text='Invitación pendiente de aceptar')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.organization')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='BatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=100)),
                ('boxes', models.PositiveIntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_rejected', models.BooleanField(default=False)),
                ('packing_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_items', to='core.packingversion')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('internal_ref', models.CharField(help_text='Ej: EXP-001', max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('SC_SENT', 'SC Enviado'), ('SIGNED', 'Firmado'), ('LABEL_PENDING', 'Etiqueta Pendiente'), ('LABEL_APPROVED', 'Etiqueta Aprobada'), ('PACKING', 'En Packing'), ('SHIPPED', 'Embarcado'), ('COMPLETED', 'Completado')], default='DRAFT', max_length=20)),
                ('incoterm', models.CharField(help_text='Ej: CIF, FOB, CIP', max_length=10)),
                ('destination_port', models.CharField(blank=True, max_length=255)),
                ('payment_terms', models.CharField(blank=True, max_length=255)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('booking_ref', models.CharField(blank=True, max_length=100)),
                ('vessel_name', models.CharField(blank=True, max_length=255)),
                ('etd', models.DateTimeField(blank=True, help_text='Estimated Time of Departure', null=True)),
                ('eta', models.DateTimeField(blank=True, help_text='Estimated Time of Arrival', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_shipments', to=settings.AUTH_USER_MODEL)),
                ('owner_org', models.ForeignKey(help_text='Organización dueña del embarque', on_delete=django.db.models.deletion.CASCADE, related_name='owned_shipments', to='core.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_items', to='core.shipment')),
            ],
        ),
        migrations.AddField(
            model_name='packingversion',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_versions', to='core.shipment'),
        ),
        migrations.CreateModel(
            name='MagicLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('email_sent_to', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magic_links', to='core.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='LabelApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=10)),
                ('artwork_url', models.URLField(blank=True)),
                ('plant_snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='label_approval', to='core.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='ExportDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('INVOICE', 'Factura'), ('BL', 'Bill of Lading'), ('SANITARY', 'Certificado Sanitario'), ('ORIGIN', 'Certificado de Origen'), ('PACKING_LIST', 'Packing List'), ('OTHER', 'Otro')], max_length=20)),
                ('file_url', models.URLField()),
                ('is_final', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_docs', to='core.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='ClientInstructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignee_text', models.TextField(blank=True)),
                ('notify_party', models.TextField(blank=True)),
                ('courier_address', models.TextField(blank=True)),
                ('special_marks', models.TextField(blank=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_instructions', to='core.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='SignatureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], max_length=10)),
                ('signature_name', models.CharField(blank=True, max_length=255)),
                ('rejection_comment', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('magic_link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signatures', to='core.magiclink')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='core.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alias', models.CharField(blank=True, help_text='Nombre corto o alias', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host_org', models.ForeignKey(help_text='Tu organización', on_delete=django.db.models.deletion.CASCADE, related_name='business_relations', to='core.organization')),
                ('partner_org', models.ForeignKey(help_text='Tu cliente/proveedor', on_delete=django.db.models.deletion.CASCADE, related_name='partner_of', to='core.organization')),
            ],
            options={
                'verbose_name': 'Business Relation',
                'verbose_name_plural': 'Business Relations',
                'unique_together': {('host_org', 'partner_org')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='packingversion',
            unique_together={('shipment', 'version_number')},
        ),
        migrations.CreateModel(
            name='ShipmentParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_type', models.CharField(choices=[('SELLER', 'Vendedor'), ('BUYER', 'Comprador'), ('CONSIGNEE', 'Consignatario'), ('NOTIFY', 'Notify Party')], max_length=15)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_participations', to='core.organization')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='core.shipment')),
            ],
            options={
                'unique_together': {('shipment', 'organization', 'role_type')},
            },
        ),
    ]
