# Generated by Django 6.0.1 on 2026-01-27 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Salmones del Sur S.A.', max_length=255)),
                ('tax_id', models.CharField(help_text='RUT: 76.xxx.xxx-k', max_length=50, unique=True)),
                ('plan_type', models.CharField(choices=[('BASIC', 'Basic'), ('PRO', 'Pro')], default='BASIC', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PackingVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='ClientPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commercial_name', models.CharField(help_text='Ej: Fish USA Inc', max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('tax_id_foreign', models.CharField(blank=True, max_length=100)),
                ('default_address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(help_text='Ej: juan@salmones.cl', max_length=254, unique=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador'), ('OPERADOR', 'Operador'), ('PLANTA', 'Planta')], default='OPERADOR', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(help_text='Ej: Lote-A', max_length=100)),
                ('boxes', models.PositiveIntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_rejected', models.BooleanField(default=False)),
                ('packing_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_items', to='core.packingversion')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_ref', models.CharField(help_text='Ej: EXP-001', max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('SIGNED', 'Firmado'), ('SHIPPED', 'Embarcado')], default='DRAFT', max_length=10)),
                ('incoterm', models.CharField(help_text='Ej: CIP, FOB, CIF', max_length=10)),
                ('booking_ref', models.CharField(blank=True, help_text='Ej: NAV-9988', max_length=100)),
                ('vessel_name', models.CharField(blank=True, help_text='Ej: LAN Cargo 501', max_length=255)),
                ('etd', models.DateTimeField(blank=True, help_text='Estimated Time of Departure', null=True)),
                ('eta', models.DateTimeField(blank=True, help_text='Estimated Time of Arrival', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='core.clientpartner')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='SalesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Ej: SKU-TRIM-D', max_length=50)),
                ('description', models.CharField(help_text='Ej: Salmon Filete Trim D', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_items', to='core.shipment')),
            ],
        ),
        migrations.AddField(
            model_name='packingversion',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_versions', to='core.shipment'),
        ),
        migrations.CreateModel(
            name='LabelApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=10)),
                ('artwork_url', models.URLField(blank=True)),
                ('plant_snapshot', models.JSONField(default=dict, help_text='Códigos congelados')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='label_approval', to='core.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='ExportDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('INVOICE', 'Factura'), ('BL', 'Bill of Lading'), ('SANITARY', 'Certificado Sanitario'), ('ORIGIN', 'Certificado de Origen'), ('OTHER', 'Otro')], max_length=20)),
                ('file_url', models.URLField()),
                ('is_final', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_docs', to='core.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='ClientInstructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignee_text', models.TextField(blank=True)),
                ('notify_party', models.TextField(blank=True)),
                ('courier_address', models.TextField(blank=True, help_text='Dirección DHL Final')),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_instructions', to='core.shipment')),
            ],
            options={
                'verbose_name_plural': 'Client Instructions',
            },
        ),
        migrations.AlterUniqueTogether(
            name='packingversion',
            unique_together={('shipment', 'version_number')},
        ),
    ]
