# Generated by Django 6.0.1 on 2026-01-29 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='created_by_org',
            field=models.ForeignKey(blank=True, help_text='Organización que creó esta shadow org (solo para UNCLAIMED)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shadow_orgs', to='core.organization'),
        ),
    ]
