# Generated by Django 6.0.1 on 2026-01-28 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='currency',
            field=models.CharField(default='USD', help_text='Ej: USD, EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='shipment',
            name='destination_port',
            field=models.CharField(blank=True, help_text='Ej: Aarhus, Denmark', max_length=255),
        ),
        migrations.AddField(
            model_name='shipment',
            name='payment_terms',
            field=models.CharField(blank=True, help_text='Ej: 30 days from BL date', max_length=255),
        ),
        migrations.CreateModel(
            name='MagicLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('email_sent_to', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magic_links', to='core.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='SignatureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], max_length=10)),
                ('signature_name', models.CharField(blank=True, max_length=255)),
                ('rejection_comment', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('magic_link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signatures', to='core.magiclink')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='core.shipment')),
            ],
        ),
    ]
