# Generated by Django 6.0.1 on 2026-01-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_shipment_currency_shipment_destination_port_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientpartner',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Email del contacto principal para notificaciones', max_length=254),
        ),
    ]
