# Generated by Django 6.0.1 on 2026-01-29 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_created_by_org_to_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='buyer_email',
            field=models.EmailField(blank=True, help_text='Email donde enviar documentos', max_length=254),
        ),
    ]
